version: "2.4"

services:
  db:
    image: postgis/postgis:12-3.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
