# Generated by Django 3.2 on 2022-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
