# Generated by Django 3.2 on 2022-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personApp", "0002_alter_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="payments",
            field=models.ManyToManyField(
                through="personApp.Transaction", to="personApp.Payment"
            ),
        ),
    ]
